a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
print("Sum is:",(a+b))
print("Difference is:",(a-b))
print("Product is:",(a*b))
print("Quotient is:",(a/b))
print("Remainder is:",(a%b))
print("Exponential result is:",(a**b))
print("The integral part of quotient is:",(a//b))